### ISSUE TITLE
Create carpool wireframes for android 

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#44]
Currently we have workflow defined in [functionality description](https://github.com/vilnius/vilnius-carpool/wiki/Functional-view) and even some kind of the implementation of it, which could be presented as [view states](https://github.com/vilnius/vilnius-carpool/wiki/Development-view#view-states---wireframe).

Please create wireframe containing following views:
- landing page #45
- new trip form
- notifications view
- "MatchedTrips" - #49 matching trip view (shown after rider gets notification) allows to request a trip
- "RequestTrip" - #65
- "ShowDrive" - where requests for drive could be accepted / rejected
- "ShowPickup" - after trip is confirmed it should show where rider should approach (shows stop and driver on map)
- "ShowItinerary" - shows trip with stops for a driver and all riders approaching to those stops

Consult @VaivaK for details on each view

**Comment by spastai** [comment]
Based on Tue discussion I have updated 
https://github.com/vilnius/vilnius-carpool/wiki/Functional-view#wireframe
Vaiva please put comments here - is the picture according our agreements.

Later we will assign this task to Renat asking to draw missing pictures

**Comment by spastai** [comment]
Implement view as shown in
[![](https://raw.githubusercontent.com/vilnius/vilnius-carpool/master/docs/mvp-flow/wrf-landing.png)](https://github.com/vilnius/vilnius-carpool/issues/44)

**Comment by VaivaK** [comment]
Hi everyone, Marijus - thank you for putting it together! My comments are below:
1. Login - can we add also G login? I know, it's an extra, but if it's not too complicated to develop i would go for it. I checked statistics so login with fb takes 46%, login with G 34%. Aim - make the login as fast as possible for most of our users.
2. Landing - a) we need to add "time" to the search part. b) (from rider perspective, in the offers part) add a button "to join the ride" directly here next to the ride information, for example instead of user icon or somewhere else. The aim - let person to request to join the ride without opening explicit information about it (view 2).
3. Landing + Your trips and other places that logical - we need to implement an icon showing that you are a driver in an easy way. We were discussing about something like simple little car sign next to information about the trip. It will help to easy divide weather the trip is from driver or rider perspective. Why do we need that? Cause 1 person may create several trips with different perspective and we want to give an opportunity to understand which perspective it is at a one glance to the information (specially on "Your trips" were it will show all your registered trips from one or both perspectives).
4. Edit trip (View 3) - if there is no matching trips for your request, you push a "+" to add trip. I would also call it "Add trip" instead of "Edit trip" as in the future it could mean different things. @spastai could you change that in your picture? It takes information automatically from the one was putten to the search but you may still edit it and save it. I would use "save" instead of "submit" for simple UX purpose cause people are more used to this word.
5. Language language. It's more a discussion then a comment. We kind of agreed on doing only one language (Lithuania) in the beginning, am i right @spastai @ArnoldasSid But i really hate Lithuanian expressions for "Save", "Login" etc, cause: 1. many young people are more used to english expressions then lithuanian 2. lithuanian ones usually takes more space, has more letters. What we can do about it? Would it crazy prolong to develop 2 languages?
6. Your trips (View 4) - as Marijus wrote - it's a list of your submitted (saved) trips from both perspectives - rider and driver (if you have both of them). Here the icon of "Driver" is most important :-) No user icons. But we need an additional icons for: a) driver perspective trip - icon (number or smth) that shows how many accepted passengers you already have. I would think of having one more icon for number of request to join your trip from riders, but i'm not sure if can make it nicely without making a mess. Maybe in the field were now we have user icons make 2 signs that indicates 2 messages - already accepted (busy seats) and pending requests. What do you think @RenatBuga @spastai @ArnoldasSid ?  b) from driver perspective i also see my trip duration (same as rider sees his trip, just there is no walking) and this number will change according to accepted requests from riders (we will add several minutes to the whole trip duration with every accepted request).
7. We have agreed if you an alert (request, new accept for your request etc the get the the number of alerts on a bell sign and the trip that alerts are connected with on "Your trips" list is bold (like unread email). 
8. Matched trips View 5  - it's from rider perspective. You push on your trip (if in the beginning when you searched there was no option to join a ride and you saved as a potential rider request) that has finally some drivers matching your request. It's similar to landing page only i would add a button "to join the ride" directly here, for example instead of user icon or somewhere else. The aim - let person to request to join the ride without opening explicit information about it (view 2). Same change should apply for landing page. 
9. Rider requests ride View 2 - all good except i would take out the From To part cause we have the information below. 
10. View 6, 7 and 8 i leave for later. Let me know when you will be coming close to it ;-)

**Comment by VaivaK** [comment]
Sorry, few more comments:
11. Rider requests ride View 2 - there is also no + at the bottom. 
12. my previous comment no 6, the part "I would think of having one more icon for number of request to join your trip from riders, but i'm not sure if can make it nicely without making a mess. Maybe in the field were now we have user icons make 2 signs that indicates 2 messages - already accepted (busy seats) and pending requests. What do you think @RenatBuga @spastai @ArnoldasSid ?" . Perfectly we would see "waiting for accept" and accepted numbers / icons from driver perspective.
13. My comments 8 - i made a mess. Sorry. There is 2 options how to do it and i would really like your opinion on it @RenatBuga purely from UX side. a) we can do that in "Your trips" you see unique trips list and then, pushed on one trip to go to that particular trip and there you see option of drivers (if there is more then one) that are matching with your request. And then you can request to join the ride directly in this screen or open explicit information and request from there. b)in "Your trips" you see not a unique trips, but list of same trip if there is different activity. I mean if i need a ride at 8 am form akropolis to europa it's a unique ride, i saved the request today in the evening and by tomorrow morning there are 3 drivers that suit my request. SO in this case i see all 3 ride possibilities and i can send request directly from here or go to explicit information and request from there. What is the difference? We just save one screan. How do you think Renat, what is better?

**Comment by spastai** [comment]
1. Adding G+ shouldn't be big extra - lets aim for this.
2. Changed 
3. Adding multilanguage support would save a lot of time in the future
4. a) Agree

**Comment by RenatBuga** [comment]
Got few more new screens in the prototype and modified the structure: **https://www.flinto.com/p/5567b4e5**
- [Login/Signup screen](https://cloud.githubusercontent.com/assets/15831041/14581031/001abbf4-03ea-11e6-8a86-78123b55302d.png)
- [Ride offers > All](https://cloud.githubusercontent.com/assets/15831041/14581039/2e074fa0-03ea-11e6-8a22-20250eda9373.png)
- [Ride offers > All > Detail offer](https://cloud.githubusercontent.com/assets/15831041/14581041/3c09e7b6-03ea-11e6-99ae-784d43452c79.png)
- [Ride offers > All > Detail offer > Directions](https://cloud.githubusercontent.com/assets/15831041/14581046/5498f470-03ea-11e6-850e-b0314c6f6274.png)
- [Ride offers > Search results](https://cloud.githubusercontent.com/assets/15831041/14581048/60f7b81e-03ea-11e6-8ef2-10a228c2a7c2.png)
- [Ride offers > Search results > Detail offer](https://cloud.githubusercontent.com/assets/15831041/14581051/6889ccfc-03ea-11e6-9708-395af5fa12e9.png)

**Comment by RenatBuga** [comment]
Added view **New ride offer** with corresponding dialogs:
- [New offer](https://cloud.githubusercontent.com/assets/15831041/14583652/b60a1374-0430-11e6-820f-506818923823.png)
- [New offer (filled with data)](https://cloud.githubusercontent.com/assets/15831041/14583653/ba304748-0430-11e6-9ef9-9704b47639d3.png)
- [New offer > Select date and time](https://cloud.githubusercontent.com/assets/15831041/14583656/c6b7548e-0430-11e6-93cd-03b8d8b963ac.png)
- [New offer > Select days](https://cloud.githubusercontent.com/assets/15831041/14583657/cb847ac8-0430-11e6-964f-5ae2ff696d01.png)
- [New offer > Alert dialog on closing](https://cloud.githubusercontent.com/assets/15831041/14583655/c159975e-0430-11e6-9b87-bd4b3f98fc1b.png)

To see it in action tap on ( + ) button in [prototype](https://www.flinto.com/p/5567b4e5).

**Comment by spastai** [comment]
@RenatBuga what is the meaning of
- [Ride offers > All > Detail offer](https://cloud.githubusercontent.com/assets/15831041/14581041/3c09e7b6-03ea-11e6-99ae-784d43452c79.png)

@ArnoldasSid any progress on #45 ? I think we need some component for trip search / filtering. Could you do this?

I will start working on #65

**Comment by RenatBuga** [comment]
@spastai: if you tap on an offer from the [list of rides with no search inputs](https://cloud.githubusercontent.com/assets/15831041/14581039/2e074fa0-03ea-11e6-8a22-20250eda9373.png), than you see this screen.

If you make a search query and access the offer from [search results](https://cloud.githubusercontent.com/assets/15831041/14581048/60f7b81e-03ea-11e6-8ef2-10a228c2a7c2.png), then you will see the [Offer details screen](https://cloud.githubusercontent.com/assets/15831041/14581051/6889ccfc-03ea-11e6-9708-395af5fa12e9.png) where the route includes your From/To address.

**Comment by ArnoldasSid** [comment]
Was thinking about landing page for already logged in users, maybe it could be something like this? (I think trafi and airbnb use something similar)
![screenshot from 2016-04-18 03 39 20](https://cloud.githubusercontent.com/assets/10629957/14591294/41abe006-0517-11e6-97f3-5d8a01cc91f8.png)

Also we need to decide on navigation. Because now we have tabs at bottom and hamburger menu at top. (Shouldn't we go with tabs at top because that's android standard?)

**Comment by RenatBuga** [comment]
We discussed at meetup the issue of the search against the list of all available rides. 
We have a [search option](http://i.imgur.com/SJkXYdl.png), but not imposed as the only door to the offers. If you force users to use the search you have very little chance of finding good trip matches, as there will be quite a few offers, at least in the beginning. Otherwise, you risk offering routes where the rider has to walk 2km to the departure point of the ride and another 3km from the driver's destination to his own point of destination.

Why search as the main door is acceptable for the following services:

**Airbnb:** If you are planning a trip to Vilnius and the search gives you the only accommodation available in Lentvaris, you can still take it. You will be using public transportation and within 30 minutes you are in the city. 

**Trafi:**  The mission of the app is to give you directions to any destination using public transportation.
In most cities, public transport infrastructure is designed so that you will always find a bus stop near your home. Whatever are your points of origin and destination, you will get the most optimal route, where you have to walk as little as possible.

**Uber/Lyft:** Whatever is your Departure and Destination, the driver will take you from point to point.

**Comment by spastai** [comment]
I have also updated our "wireframe" - https://github.com/vilnius/vilnius-carpool/wiki/Functional-view#wireframe

**Comment by RenatBuga** [comment]
Regarding the bottom bar. This is not a stigma for Android applications, which prohibits the use of it. Take as examples [Google+](https://cloud.githubusercontent.com/assets/15831041/14597848/eaf5152a-0557-11e6-9833-437ec24d823b.png) and [Dropbox](https://cloud.githubusercontent.com/assets/15831041/14597916/64492fba-0558-11e6-98f6-85bad40c1f51.png).  The bottom bar provides one-tap access to the main sections of the app.

I would love to see sketches of ideas for better application structure.

**Comment by spastai** [comment]
@RenatBuga I have updated https://github.com/vilnius/vilnius-carpool/wiki/Functional-view#wireframe according your last wireframes. Few notes:
1. In my drawing I'm using green color for driver path (green light for your trip) and blue (something out of blue) to mark uncertainty of the rider. Maybe it would be reasonable to change colors in the screens also (now they are opposite - offers are in blue).
2. In the notifications view 1st notification has buttons Accept / review - wouldn't be reasonable to change "Accept" into "Confirm"
3. In the notifications view 2nd notification has buttons Accept / review - wouldn't be reasonable to change "Accept" into "Request" ?
4. Reviewing "Ride request" (https://www.flinto.com/p/5567b4e5)  it would be good to know at least how many passengers you have accepted already

**Comment by RenatBuga** [comment]
@spastai
1. Navigation bar colors can be changed easily inside the code. Too much
   work for photoshop.
   2, 3. Changed
2. To make things easier for everyone: beta testers, developers, designers,
   and get the app launched soon, my suggestion is to limit one passenger per
   trip.
