### ISSUE TITLE
Login page should call for action to proceed.

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#93]
Initially login page was designed as landing page (see [http://stg.arciau.lt/login](http://stg.arciau.lt/login).
In current workflow it appears when trying to access secured screens (like your trips), thus design should it be changed.

**Comment by RenatBuga** [comment]
If you force users to login with either FB or G+, you won't need the login page again. My suggestion is to remove the anonymous browsing for MVP. It will reduce a good amount of work.

**Comment by VaivaK** [comment]
For first version there will be no anonymous browsing, but we need to add it asap for next versions. And for this it would be good to think ahead so the workflow could stay similar and we wouldn't need to start everything from the scratch. And for future versions browsing with mandatory login is not really an option, as first product must rise interest and show value to client, not force him to register. Don't you agree?

**Comment by RenatBuga** [comment]
I believe in MVP approach and listening to users. Very often developers
make the mistake by developing a complex product rich in functionalities
but once the product is launched realize that users want things work other
way. My advice is not to plan ahead. Make the very minimal viable product
and launch it.

On Tuesday, May 17, 2016, VaivaK notifications@github.com wrote:

> For first version there will be no anonymous browsing, but we need to add
> it asap for next versions. And for this it would be good to think ahead so
> the workflow could stay similar and we wouldn't need to start everything
> from the scratch. And for future versions browsing with mandatory login is
> not really an option, as first product must rise interest and show value to
> client, not force him to register. Don't you agree?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/vilnius/vilnius-carpool/issues/93#issuecomment-219637805

## 

Onward and Upward,

## 

Renat Buga

http://atviras.vilnius.lt/iniciatyvos/code-for-vilnius
_http://codeforvilnius.lt http://codeforvilnius.lt_

**Comment by VaivaK** [comment]
Thank you Renat and you are absolutely right. It happens too many times when product people get stuck on developing product instead of asking. Usually, after 2 years of developing and polishing the product, the clients simply don't like it. But about login - it's different. It's not about polishing and making the product perfect. It's about psychology and there is too many researches behind it (and experience too) not to follow and not to think of that ahead. simple business logic.
Maybe there is a way, middle point, how to adjust the design so it would fit for both ways. I no, middle point is usually a worst point, but maybe we could try to find a solution, that is if not perfect, but good enough?

**Comment by VaivaK** [comment]
If not - @spastai please more forward as it is now for the moment, we will find a solution later for this change.
